/* stardust block capabilities — template-slotted (markup baked so the DA pipeline can't strip inline SVG). */
const HTML = "\n    <div class=\"wrap cap-split\">\n      <div class=\"cap-rail\" data-reveal>\n        <h2>One Integrated Team. Every Channel. Full Accountability.</h2>\n        <p class=\"lede\">Every capability your growth needs, operated under one strategy, one team, and one accountable plan. Explore the <a href=\"/services\">full service offering</a> or browse the core capabilities below.</p>\n        <a class=\"text-link\" href=\"/services\">Explore all services <span class=\"arr\" aria-hidden=\"true\">&rarr;</span></a>\n        <div class=\"exhibit\">\n          <span class=\"val\">Spence Diamonds: +61% online sales</span>\n          <span class=\"src\">Client outcome &middot; marketFX client results</span>\n        </div>\n      </div>\n      <div class=\"cap-grid\">\n        <div class=\"cap-card\" data-reveal>\n          <h3><a href=\"/digital-marketing-strategy\">Strategic Planning <span class=\"arr\" aria-hidden=\"true\">&rarr;</span></a></h3>\n          <p>Market intelligence, customer journey mapping, and commercial strategy aligned to revenue goals.</p>\n        </div>\n        <div class=\"cap-card\" data-reveal>\n          <h3><a href=\"/paid-media-services\">Performance Media <span class=\"arr\" aria-hidden=\"true\">&rarr;</span></a></h3>\n          <p>Paid search, social advertising, and programmatic buying optimized for ROAS.</p>\n        </div>\n        <div class=\"cap-card\" data-reveal>\n          <h3><a href=\"/seo-and-ai-visibility-consulting\">SEO &amp; Content <span class=\"arr\" aria-hidden=\"true\">&rarr;</span></a></h3>\n          <p>Technical SEO, content strategy, and authority building for sustainable organic growth.</p>\n        </div>\n        <div class=\"cap-card\" data-reveal>\n          <h3><a href=\"/content-strategy-services\">Creative Production <span class=\"arr\" aria-hidden=\"true\">&rarr;</span></a></h3>\n          <p>Campaign creative, brand assets, and content that converts across every channel.</p>\n        </div>\n        <div class=\"cap-card\" data-reveal>\n          <h3><a href=\"/services\">Social &amp; Community <span class=\"arr\" aria-hidden=\"true\">&rarr;</span></a></h3>\n          <p>Strategic social management, community building, and sentiment-driven engagement.</p>\n        </div>\n        <div class=\"cap-card\" data-reveal>\n          <h3><a href=\"/services\">CRM &amp; Retention <span class=\"arr\" aria-hidden=\"true\">&rarr;</span></a></h3>\n          <p>Email, SMS, loyalty programs, and lifecycle marketing that maximizes customer value.</p>\n        </div>\n      </div>\n    </div>\n  ";
export default function decorate(block) {
  const el = document.createElement('section');
  
  el.setAttribute('data-section', "capabilities");
  el.innerHTML = HTML;
  block.replaceChildren(el);
  block.classList.remove("capabilities");
}
