/* stardust block insights — template-slotted (markup baked so the DA pipeline can't strip inline SVG). */
const HTML = "\n    <div class=\"wrap\">\n      <div class=\"insights-head\" data-reveal>\n        <h2>Expert perspectives on what actually works.</h2>\n        <a class=\"text-link\" href=\"/blog\">View all articles <span class=\"arr\" aria-hidden=\"true\">&rarr;</span></a>\n      </div>\n      <div class=\"article-grid\">\n        <article class=\"article\" data-reveal>\n          <div class=\"thumb\"><img src=\"https://marketfxdigital.com/assets/fragmented-agencies-preview-wbvfrokt.webp\" alt=\"Disconnected paper marketing icons linked by dashed lines illustrating fragmented agency work\" width=\"1448\" height=\"1086\" loading=\"lazy\"></div>\n          <p class=\"cat\">Strategy</p>\n          <h3><a href=\"/blog/fragmented-marketing-agencies-roi\">Why Fragmented Marketing Agencies Are Costing You More Than You Think</a></h3>\n          <p>The hidden cost of juggling multiple vendors isn't just budget waste. It's the strategic gaps between them that silently erode your growth.</p>\n          <a class=\"text-link\" href=\"/blog/fragmented-marketing-agencies-roi\">Read article <span class=\"arr\" aria-hidden=\"true\">&rarr;</span></a>\n        </article>\n        <article class=\"article\" data-reveal>\n          <div class=\"thumb\"><img src=\"https://marketfxdigital.com/assets/omnichannel-retail-preview-BdAdqAWb.webp\" alt=\"Isometric diagram of multi-location retail stores connected to digital channels and a central hub\" width=\"1448\" height=\"1086\" loading=\"lazy\"></div>\n          <p class=\"cat\">Retail</p>\n          <h3><a href=\"/blog/omnichannel-marketing-multi-location-retail\">Omnichannel Marketing for Multi-Location Retail</a></h3>\n          <p>What actually works when you're coordinating marketing across dozens of locations with different competitive landscapes.</p>\n          <a class=\"text-link\" href=\"/blog/omnichannel-marketing-multi-location-retail\">Read article <span class=\"arr\" aria-hidden=\"true\">&rarr;</span></a>\n        </article>\n        <article class=\"article\" data-reveal>\n          <div class=\"thumb\"><img src=\"https://marketfxdigital.com/assets/ai-marketing-preview-X-pT6ZHR.webp\" alt=\"Marketer reviewing AI-organized dashboards turning chaotic inputs into structured marketing outputs\" width=\"1448\" height=\"1086\" loading=\"lazy\"></div>\n          <p class=\"cat\">AI &amp; Automation</p>\n          <h3><a href=\"/blog/ai-in-marketing-what-actually-changes\">AI in Marketing: What Actually Changes</a></h3>\n          <p>Separating the genuine transformation from the hype, and what marketing leaders should prioritize right now.</p>\n          <a class=\"text-link\" href=\"/blog/ai-in-marketing-what-actually-changes\">Read article <span class=\"arr\" aria-hidden=\"true\">&rarr;</span></a>\n        </article>\n      </div>\n    </div>\n  ";
export default function decorate(block) {
  const el = document.createElement('section');
  
  el.setAttribute('data-section', "insights");
  el.innerHTML = HTML;
  block.replaceChildren(el);
  block.classList.remove("insights");
}
